### ISSUE TITLE
Current master code is not update to the 0.7.0-SNAPSHOT artifact

### ISSUE THREAD

**Issue by nizanifrach** [applicaai/spring-boot-starter-temporal#12]
The current artifact in `https://oss.sonatype.org/content/repositories/snapshots/</url` repository is not updated to current master code.
Currently `ActivityAnnotationBeanPostProcessor ` is not scanning the TemporalActivity annotation.
Is there a solution for it?

**Comment by simcha** [comment]
Hi as of 1 issue "The current artifact in https://oss.sonatype.org/content/repositories/snapshots/</url repository is not updated to current master code." I'm not sure why you say so (I  am using this version from that repository) but in case it is really not I did a publish again. 
And I do not understand second part: what kind of error it causes? Or putting it else what you would like to achieve?
