### ISSUE TITLE
[Feature Request] Allow specifying temporal namespace

### ISSUE THREAD

**Issue by nvtkaszpir** [applicaai/spring-boot-starter-temporal#13]
Looks like the library allows only to use `default` namespace.
Would be nice to allow to use custom namespaces if required.

https://docs.temporal.io/docs/concept-namespaces

**Comment by simcha** [comment]
Sory for long answer. First you are right we need to add this to config. But if I understand it well you need only to add it here:
```
@Configuration
public class TestTemporalOptionsConfiguration implements TemporalOptionsConfiguration {

  @Override
  public Builder modifyClientOptions(Builder newBuilder) {
    newBuilder.setNamespace("mynamespace");
    return newBuilder;
  }
}
```

**Comment by simcha** [comment]
It is done in 0.10
