### ISSUE TITLE
[Feature Request] Support for cron workflows

### ISSUE THREAD

**Issue by pvolchak** [applicaai/spring-boot-starter-temporal#20]
Would be really great to have a cronworkflow support using annotations.

**Comment by pvolchak** [comment]
is it possible for me to create a pr to do that? i got this to support the cron 
<img width="1083" alt="Screen Shot 2021-08-30 at 2 25 12 PM" src="https://user-images.githubusercontent.com/43765212/131400683-e431073e-a7cb-461f-ac15-2bc62fa9f3b0.png">
<img width="443" alt="Screen Shot 2021-08-30 at 2 25 35 PM" src="https://user-images.githubusercontent.com/43765212/131400732-1fb4df07-b1f1-4d95-9db7-713905e34ca3.png">
<img width="474" alt="Screen Shot 2021-08-30 at 2 25 51 PM" src="https://user-images.githubusercontent.com/43765212/131400779-219b683e-593b-4cd8-8a8f-cd9d2bbf32ae.png">

**Comment by simcha** [comment]
Yes sure it sounds grate.

**Comment by pvolchak** [comment]
sorry for being dumb. i cloned the repo. created the branch, but i am not getting this "ERROR: Permission to applicaai/spring-boot-starter-temporal.git denied to pvolchak". Can i request a permission or do i have to do it somehow differently?

**Comment by pvolchak** [comment]
all right. i figured it out https://github.com/applicaai/spring-boot-starter-temporal/pull/21. thanks

**Comment by simcha** [comment]
Sorry for the long time for merge.
