### ISSUE TITLE
Temporal Client not reporting metrics

### ISSUE THREAD

**Issue by jorgecmb** [applicaai/spring-boot-starter-temporal#26]
Hi there,

I noticed the Temporal Clients created using the spring-boot-starter-temporal are not reporting metrics to Prometheus. I believe it's missing a call to `setMetricsScope()` when creating the `WorkflowServiceStubsOptions` in `TemporalBootstrapConfiguration::mapWorkflowServiceStubsOptions`

Is there something in the roadmap to add this feature?

Thanks in advance.

**Comment by simcha** [comment]
I am not sure how to test that. Or maybe it is as simple as adding the call. We will do it with pleasure if we are sure what to do.

**Comment by jorgecmb** [comment]
Sorry for the delay in replying but I managed to publish client metrics by doing these changes in `TemporalBootstrapConfiguration`:

1 - Autowire `PrometheusMeterRegistry` in `TemporalBootstrapConfiguration`

2 - Add the following line to WorkflowServiceStubsOptions.Builder in `mapWorkflowServiceStubsOptions` method:
```
.setMetricsScope(buildMetricsScope())
```
so it looks like this:
```
WorkflowServiceStubsOptions.newBuilder()
    .setChannel(channel.build())
    .setMetricsScope(buildMetricsScope())
    .setEnableHttps(temporalProperties.getUseSsl());
```

3 - Add this method
```
private Scope buildMetricsScope() {
        return new RootScopeBuilder()
            .reporter(new MicrometerClientStatsReporter(prometheusMeterRegistry))
            .reportEvery(ofSeconds(10));
}
```

**Comment by simcha** [comment]
Thanks for solution

**Comment by ghost** [comment]
Are there plans to add the suggested changes?
