### ISSUE TITLE
Activity only workers

### ISSUE THREAD

**Issue by the-fine** [applicaai/spring-boot-starter-temporal#4]
Right now its possible to register an activity to a worker is by having a workflow with an ActivityStub annotated field.
It would be great to have a way to register only activities to a worker, by using a new annotation on it maybe?

**Comment by simcha** [comment]
Dear Alex I do not fully understand what you will like to achieve? You will like to register activity stubs that:
1) are not spring services,
2) are not in same jar,
3) sommeting else?

**Comment by the-fine** [comment]
Sorry for not giving an example.
I would like to be able to have the following:
One spring boot service with workflow impl and activity stubs and another spring boot service with activity impl.
That means that in the first service only the workflow will be registered to the worker and in the second service only the activities will be registered to the worker

**Comment by simcha** [comment]
I did not even know one can do something like that. So how would you do that with no spring. Create an empty worker and add activities? In one microservice and register worker with implementation of the workflow in the other? 
Not registering activities will be simple we only need to know whether we like to have it in configuration or a code? But the second part eg. no workflow but registering activities. For now I don't know how to do it.

**Comment by the-fine** [comment]
You have an example over here https://docs.temporal.io/docs/java-quick-start#activities which basically only calls registerActivitiesImplementations.
I would do this with code, from my point of view it will be two separate code bases.
I would add a new annotation(TemporalActivity) and an annotation processor that will create a worker and register these activities

**Comment by simcha** [comment]
OK so you would like a `ActivityStub` annotation to have an option `createWorker` default being `true` on the workflow implementation so you can set it to `false`. And second annotation the one you named `TemporalActivity` instead of `Service` from spring with option `createWorker` set to `false` that you can set to `true`. We can add these option to `TemporalWorkflow` for consistency and add configuration options for everyone so one can have same codebase.

**Comment by the-fine** [comment]
Sounds good to me, the only point I'm not sure I get is about `TemporalWorkflow`, can you elaborate?

**Comment by the-fine** [comment]
@simcha not sure if you missed my comment.
BTW, i didnt ment that `TemporalActivity` shouldn't be a spring `Service`

**Comment by simcha** [comment]
@the-fine sorry for the delay. The pull request is here and shall be reviewed and merged in the beginning of next week. You can see on the pull request that finally it is even simpler that we thought.

**Comment by simcha** [comment]
Done
