### ISSUE TITLE
Suggestion - Rename library based on Spring Boot naming convention

### ISSUE THREAD

**Issue by thiagolocatelli** [applicaai/spring-boot-starter-temporal#5]
`spring-boot-starter-*` is the naming convention for official spring boot starter libraries. For community and non-official libraries, the suggestion name is `*-spring-boot-starter`, so I would suggest changing it to `temporal-spring-boot-starter`.

**Comment by thiagolocatelli** [comment]
Also, publish the jar files. I am not able to use the following dependency

```
<dependency>
	<groupId>com.github.applicaai</groupId>
	<artifactId>spring-boot-starter-temporal</artifactId>
	<version>0.5.1-SNAPSHOT</version>
</dependency>
```

**Comment by simcha** [comment]
As for this one thanks it's published now (checked on gradle so not sure for maven)
> Also, publish the jar files. I am not able to use the following dependency
As for the first one it is little bit more tricky.

**Comment by thiagolocatelli** [comment]
@simcha publish to maven so it is available for both gradle and maven. I wanted to use and I have maven projects here.

**Comment by kartikv11** [comment]
+1 unable to use the dependency in maven. Can you please publish this?

**Comment by simcha** [comment]
@thiagolocatelli  and @kartikv11 I am sorry but I fail to understand were you want me to publish. The  0.5.1-SNAPSHOT was just forgotten and hence unobtainable but what is a difference from gradle to maven publishing?

**Comment by kartikv11** [comment]
@simcha 
The ask was to have this dependency published to [central maven repository](https://repo1.maven.org/maven2/).
Since, this repository is not published as a dependency, we are required to build this locally to use it in our project.

**Comment by simcha** [comment]
Ok I will try to fix that. For now is it not enough to add https://oss.sonatype.org/content/repositories/snapshots/ to the repository list in maven?

**Comment by kartikv11** [comment]
@simcha This works. Thanks :)

**Comment by simcha** [comment]
I will try to fix this but honestly cant find easy way to do it (t is probably so easy that no one is informing about it).
